### ISSUE TITLE
发起动态

### ISSUE THREAD

**Issue by iyear** [iyear/biligo#5]
包括定时发布

**Comment by lb-chc** [comment]
Hi，想问一下哪些接口会被认为直接涉及滥用的？

**Comment by iyear** [comment]
> Hi，想问一下哪些接口会被认为直接涉及滥用的？

天选之人抽奖、动态抽奖等直接涉及到的接口，其实只是个免责声明

**Comment by iyear** [comment]
close
153575bc50989dbc283e6a55301916f84c3df71e
